sudo: required
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - PATH=$PATH:~/google-cloud-sdk/bin
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CLOUDSDK_PYTHON_SITEPACKAGES=1
cache:
  directories:
    - ~/google-cloud-sdk
    - ~/docker
addons:
  code_climate: true
install:
  - pip install pyopenssl
before_script:
  - scripts/check-install-gcloud.sh
  - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
  - docker build -t $GCLOUD_IMAGE:$TRAVIS_BUILD_ID .
  - mkdir -p ~/docker; docker save $GCLOUD_IMAGE:$TRAVIS_BUILD_ID > ~/docker/image.tar
  - npm install -g bower eslint codeclimate-test-reporter
  - npm install
  - bower install
script:
  - npm run test
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    repo: abramz/short-url-front-end
    branch: master
